# Welcome to Jekyll!

title: C <i class="fa fa-heartbeat icon-red"></i> L
email: jeepchenup@foxmail.com
# description: 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.51leif.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  jeepchenup

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
